spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/${POSTGRES_DB:location-db}
#    url: jdbc:postgresql://ewm-db:5432/${POSTGRES_DB:ewm-main}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update  # Автоматическое создание или обновление таблиц
    show-sql: true  # Показывать SQL-запросы в логах
    properties:
      hibernate:
        format_sql: true  # Форматирование SQL-запросов для удобочитаемости

  cloud:
    openfeign:
      okhttp:
        enabled: true

server:
  port: 0

statsService:
  url:
  name: stats-service

admin:
  user:
    service:
      url:
  events:
    service:
      url:

resilience4j.circuitbreaker:
  instances:
    myService:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true