spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
      discovery:
        enabled: true
        serviceId: config-server

    loadbalancer:
      retry:
        enabled: true
        retry-on-all-operations: true
      service-discovery:
        timeout: 1s

    gateway:
      httpclient:
        connect-timeout: 1000000
        response-timeout: 5m

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    fetch-registry: true
    registry-fetch-interval-seconds: 2

  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

server:
  port: 8080




