spring:
  cloud:
    gateway:
      routes:
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path= /categories/**, /admin/categories/**

        - id: compilation-service
          uri: lb://COMPILATION-SERVICE
          predicates:
            - Path= /admin/compilations/**, /compilations/**

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path= /events/**, /users/{userId}/events, /users/{userId}/events/{eventsID}, /admin/events,
              /admin/events/{eventId}

        - id: location-service
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path= /locations/**, /admin/locations/**

        - id: request-service
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path= /users/{userId}/requests/**, /users/{userId}/requests/{requestId}/cancel,
              /users/{userId}/events/{eventId}/requests, requests/events/{eventId}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /admin/users/**, admin/users/{userId}/**

        - id: stat-service
          uri: lb://STATS-SERVICE
          predicates:
            - Path=/hit, /stats/**