spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        schema.registry.url: http://localhost:9102
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

server:
  port: 0

collector:
  topic:
    stats:
      user-actions:
        v1: stats.user-actions.v1

grpc:
  server:
    port: ${COLLECTOR_GRPC_PORT:0}