spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:ewm-stats}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update  # Автоматическое создание или обновление таблиц
    show-sql: true  # Показывать SQL-запросы в логах
    properties:
      hibernate:
        format_sql: true  # Форматирование SQL-запросов для удобочитаемости

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/